### ISSUE TITLE
Update japanese docs

### ISSUE THREAD

**Issue by taliaga** [smartsdk/guided-tour#15]
Issue to batch updates of docs in English that need to be reflected in Japanese when translators are available.

- [ ] https://github.com/smartsdk/guided-tour/pull/14

**Comment by fisuda** [comment]
After #14 is merged, I will update the swarmcluster.md file in docs.ja, and fix line length beyond 80 in quantumleap.md in docs.ja.

**Comment by taliaga** [comment]
https://github.com/smartsdk/guided-tour/pull/14 is now merged

**Comment by fisuda** [comment]
Thank you for letting me know. I will translate them and send PR.
